name: cloudevents

on:
  pull_request:
    paths:
      - cloudevents/**
  push:
    tags:
      - "cloudevents/v*"

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "adopt"
          cache: gradle
      - run: ./gradlew :cloudevents:clean :cloudevents:shadowJar --no-daemon

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "adopt"
          cache: gradle

      - id: vars
        run: |
          echo "version=${GITHUB_REF#refs/tags/cloudevents/v}" >> "$GITHUB_OUTPUT"

      - run: ./gradlew :cloudevents:clean :cloudevents:shadowJar --no-daemon -Pversion=${{ steps.vars.outputs.version }}

      - name: Upload extension .jar to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cloudevents/build/libs/cloudevents-*.jar
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
